---
title: "Technology and Emigration Flows"
subtitle: Final Project Proposal
author: "Ayra Rowena Reyla and Ana Cecilia Montes"
date: "20 October 2015"
output: pdf_document
bibliography:
- referencesreylamontes.bib

highlight: zenburn
theme: united
toc: yes
toc_depth: 3
---



\newpage

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# 1 Introduction

Migration, the movement of individuals is hardly a new phenomenon in societies. People have moved from country to country for centuries, be it for social, political or economic reasons, however, more recently it has gained momentum amongst academic scholars and policy makers. According to the United Nation's Population Division, more than 231 million individuals now live outside of their home country and moreover, this number has increased rapidly in the last 10 years. Few countries today are not affected by international migration (Martin, 2014). It importance lies in the fact that international migration is part of a transnational shift that is currently reshaping societies and politics around the globe. 

Migration is one of the three main determinants of a country's population development. The other two - the birth and death rate - are generally believed to be easier to forecast (Castles, Haas and Miller, 2014). However, factors that have classically been seen as drivers for migration between two countries such as [a] conditions in the sending country driving out inhabitants, including political troubles, persecution, conflict and other "push factors"", [b] conditions in the receiving country attracting migrants, such as higher wages, better know as "pull factors", and [c] factors which facilitate or authorize the migration process itself, such as the receiving country's immigration politics. 

More recently, there been new trends that have also enhanced the population flows. Martin (2014) highlights four trends that have increased and continue to improve migration flows.  First, the demand of multinational countries to strengthen global mobility has improved the influx in _economic integration_. Secondly, the change in _geo-political and security_ has enhanced international cooperation, with autonomous countries seeking legitimate forms of transnational mobility, in a world posed with any security threats. A third trend that has portend the need for enhanced economic cooperation is the _increasing transnationalism_, whereas individual migrants hare able to maintain strong relationships and connections in two or more countries has fostered a growing acceptance of multiple-nationality. Additionally, a fourth trend that increases migration flows can be attributed to some extent to new _challenged_, such as  _climate change_ that push individuals to migrate to a new location. 

One driving factor increasingly put forward in recent years is the use of technology. According to Hiller and Franz (2004), computer mediated communication has created new possibilities for migrants to maintain strong linkages and ties with their home nations. Not only has new technology improved and heightened communication, it has also bridged cultural gap between countries as it allows people to easily gathering new information and knowledge about other cultures. This of course has made a large impact on people's perception on other cultures and their worldviews. Overall, technology has changed the landscape for communicating, and gathering knowledge and information. These revolutions that have transformed society is making travel and telecommunications cheaper and easier than ever. Moreover, Technology has enhanced the aspects of interaction as it is transforming the way individuals communicate. 

# 2 Research Question 

Has the increase use of technologies such as internet and mobile phones affected the flow of emigration?

# 3 State of the Art

When examining this topic further, it is essential to examine the already present literature and theories involved. As migration has been an ongoing phenomenon for many centuries, examining the theories will provide a strong foundation for subsequent discussion and provide a framework for the our analysis. 

According to @Castles2014 there are certain determinants that "push" and "pull" individuals out of certain regions or areas. The first "push" and "pull" model was developed by Passaris in 1989, and he can be classified as a 
_Functionalist theorist_. There here are economic, environmental, and demographic characteristics that influence an individual's choice to stay or leave a particular geographic region. There are a large number of "push" factors, among those include - population growth and density, security issues, economic opportunities, and political factors. On the other hand, the characteristics of the receiving countries may also influence people's decision to pack up and leave. These characteristics are commonly known in the literature as, "Pull" factors, much like their counterparts have a strong influence on attracting a moderate flow of people. Among them include, the demand for labor, the availability of land, economic and employment opportunities, and favorable immigration policies. 

Nevertheless, the "push" and "pull" model only accounts for causal relationships between variables and does not take into account for certain simultaneous determinate. However, this analysis will not focus on residual determinants.

Another theory common among the literature is the _Neo-classical theory_, which affirms that the market allocates labor depending on demand and supply. In most cases, the demand of employment will automatically provide a supply of persons willing to do the labor in order for the market to reach equilibrium. The determinants of the individual decision will be based on the wage differentials among two geographical areas. To illustrate, a person will be more willing to move to another for labor and employment if the offering wage is higher and more competitive than in their home market. 


Another relevant theory associated with the focus of this analysis is _Globalization theory_. According to Castles2014, Globalization can be defined as as the process in which world wide interconnections have not only expanded but have deepened the speed of connectivity, and time of all aspects of social life. This theory suggest that globalization has very inconclusive effects on migration flows. On one hand, globalization has strengthened migration since it has fostered new developments in transport and comunications. However, on the other hand, it is argued that globalization these new developments have also changed the way in which people work and interact with each other. For example, it has increased the outsourcing, communiting and teleworking. Although it sounds like a positive innovation, this has caused migration to another location less attractive, as all the resources are so readily available. 

[provide conclusion to this section of the paper, pershaps tie it back to the research question at hand :)]

#4 Relevance

Migration is a phenomenon that has been happening for centuries, and will continue to happen under any circumstances. The flow of people between countries may stagnate at times, but nevertheless it will never fully cease. In the contemporary context, communications technology will only continue to increase.There are always many reasons why individuals choose to migration, and communication technologies could make this process much more easy and attractive. I could be benificial for countries or governments in a way because it could exploit these technologies in order to communicate policies and information for people interesting in migrating. 

It is also important to undestand the causes and the drivers for migration so that the governments can futher learn and grow depending on trends currently happening around the globe. Mobile and internet technology is also a resource that governments can exploit and learn from. 


# 5 Method
## 5.1 Data Selection
In order to examine the flows of migration, we intend to to use data on trends in _International Migrant Stock_ produced by the United Nations. The data contains information from 232 countries and provides the number of migrants by destination and country of origin for four periods of time; 1990, 2000, 2010, and 2013. Moreover, to account for technology diffusion we will use _World Bank indicators_ on the number of Internet users and the number of cellular mobile subscriptions for each country. 

##5.2 Emperical Strategy

To examine the hypothesized effect of technology, cross country panel data analysis will be conducted. Our dependent variable of interest is the total number of immigrants by country, this will be our Y and the independent variable (X) we will be stuyding are number of internet users, and the number of mobile users per country. The countrol variables we plan on using include, wage differentials, economic growth, unemployment, criminal death rate, conflict and political freedoms. This research will use panel data methods to address the research question, this includes panel regressio, fixed effects and random effects. 


# 6 Limitations

One of the major limitations on migration studies is the difficulty of accessing good and reliable datasets. The United Nations (UN) have complied a large amount of statistical evidence on the topic of migration, however, the database does not have a large number of year observations. This will limit the resarch because the results will not yield complete full year to year analysis, which of course will rely mostly on between country effects. 

[define x and y variables in the data set ]

#**References**





